module.exports = {
  ROLES: {
    AUTHOR: "AUTHOR",
    ADMIN: "ADMIN"
  },

  TICKET_STATUS: {
    OPEN: "OPEN",
    IN_PROGRESS: "IN_PROGRESS",
    RESOLVED: "RESOLVED",
    CLOSED: "CLOSED"
  },

  TICKET_PRIORITY: {
    CRITICAL: "CRITICAL",
    HIGH: "HIGH",
    MEDIUM: "MEDIUM",
    LOW: "LOW"
  },

  TICKET_CATEGORY: {
    ROYALTY_PAYMENTS: "ROYALTY_PAYMENTS",
    ISBN_METADATA: "ISBN_METADATA",
    PRINTING_QUALITY: "PRINTING_QUALITY",
    DISTRIBUTION: "DISTRIBUTION",
    BOOK_STATUS: "BOOK_STATUS",
    GENERAL: "GENERAL"
  }
};